# Generated by Django 5.1.7 on 2025-03-25 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='个人简介')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性别')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='评分次数')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='评论次数')),
                ('preferred_types', models.ManyToManyField(blank=True, related_name='preferred_by_users', to='anime.animetype', verbose_name='喜好类型')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案列表',
            },
        ),
        migrations.CreateModel(
            name='UserBrowsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_browsed', models.DateTimeField(auto_now=True)),
                ('browse_count', models.PositiveIntegerField(default=1)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsed_by', to='anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '浏览记录',
                'verbose_name_plural': '浏览记录列表',
                'indexes': [models.Index(fields=['user', '-last_browsed'], name='user_browse_time_idx')],
                'unique_together': {('user', 'anime')},
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preference_value', models.FloatField(default=0, verbose_name='偏好值')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户偏好',
                'verbose_name_plural': '用户偏好列表',
                'indexes': [models.Index(fields=['user', '-preference_value'], name='user_pref_value_idx')],
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
