# Generated by Django 5.1.7 on 2025-03-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='influence_score',
            field=models.FloatField(default=0, verbose_name='用户影响力'),
        ),
        migrations.AddField(
            model_name='profile',
            name='likes_given_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞他人次数'),
        ),
        migrations.AddField(
            model_name='profile',
            name='likes_received_count',
            field=models.PositiveIntegerField(default=0, verbose_name='获得点赞次数'),
        ),
        migrations.AddField(
            model_name='profile',
            name='replies_count',
            field=models.PositiveIntegerField(default=0, verbose_name='回复次数'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_activity_score',
            field=models.FloatField(default=0, verbose_name='社交活跃度'),
        ),
    ]
