# Generated by Django 5.1.7 on 2025-03-25 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='类型描述')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='URL别名')),
            ],
            options={
                'verbose_name': '动漫类型',
                'verbose_name_plural': '动漫类型列表',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('original_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='原始标题')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL别名')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(verbose_name='描述')),
                ('cover', models.ImageField(upload_to='anime_covers/%Y/%m/', verbose_name='封面图')),
                ('release_date', models.DateField(verbose_name='发布日期')),
                ('episodes', models.PositiveSmallIntegerField(default=1, verbose_name='集数')),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='每集时长(分钟)')),
                ('popularity', models.FloatField(db_index=True, default=0, verbose_name='热门指数')),
                ('rating_avg', models.FloatField(db_index=True, default=0, verbose_name='平均评分')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='评分数量')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('favorite_count', models.PositiveIntegerField(default=0, verbose_name='收藏次数')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_completed', models.BooleanField(default=True, verbose_name='是否完结')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='anime.animetype', verbose_name='类型')),
            ],
            options={
                'verbose_name': '动漫',
                'verbose_name_plural': '动漫列表',
                'ordering': ['-popularity', '-release_date'],
                'indexes': [models.Index(fields=['type', '-popularity'], name='anime_type_pop_idx'), models.Index(fields=['type', '-rating_avg'], name='anime_type_rating_idx'), models.Index(fields=['-release_date'], name='anime_release_idx')],
            },
        ),
    ]
