# Generated by Django 5.1.7 on 2025-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['title'], name='anime_title_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['is_completed', '-popularity'], name='anime_complete_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['is_featured', '-popularity'], name='anime_featured_pop_idx'),
        ),
    ]
