# Generated by Django 5.1.7 on 2025-03-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_like_count_anime_anime_title_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞次数'),
        ),
    ]
