# Generated by Django 5.1.7 on 2025-03-30 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_like_count_anime_anime_title_idx_and_more'),
        ('recommendation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='anime.anime', verbose_name='动漫')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_likes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '动漫点赞',
                'verbose_name_plural': '动漫点赞列表',
                'indexes': [models.Index(fields=['anime', '-timestamp'], name='anime_like_time_idx'), models.Index(fields=['user', '-timestamp'], name='user_anime_like_time_idx')],
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
