# Generated by Django 5.1.7 on 2025-03-30 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_like_count'),
        ('recommendation', '0002_animelike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='animelike',
            name='anime_like_time_idx',
        ),
        migrations.RenameIndex(
            model_name='animelike',
            new_name='user_anime_like_idx',
            old_name='user_anime_like_time_idx',
        ),
        migrations.AlterField(
            model_name='animelike',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='anime.anime'),
        ),
        migrations.AlterField(
            model_name='animelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='animelike',
            index=models.Index(fields=['anime'], name='anime_like_idx'),
        ),
    ]
