# Generated by Django 5.1.7 on 2025-03-31 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_remove_animelike_anime_like_time_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animelike',
            options={'ordering': ['-timestamp'], 'verbose_name': '动漫点赞', 'verbose_name_plural': '动漫点赞列表'},
        ),
        migrations.RemoveField(
            model_name='animelike',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='animelike',
            name='updated_at',
        ),
    ]
