# Generated by Django 5.1.7 on 2025-03-31 08:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_like_count'),
        ('recommendation', '0004_alter_animelike_options_remove_animelike_created_at_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='animelike',
            new_name='anime_likes_idx',
            old_name='anime_like_idx',
        ),
        migrations.AddField(
            model_name='animelike',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='animelike',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='animelike',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_likes', to='anime.anime'),
        ),
    ]
